name: Docker Image CI

on:
  push:
    branches:
      - master/discovery-service
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: discovery-service
      run: docker build . --file /discovery-service/Dockerfile --tag discovery-service:$(date +%s)
